### ISSUE TITLE
Allow campaign keyword expansion in campaign-stage fields

### ISSUE THREAD

**Issue by marcmengel** [fermitools/poms#11]
This is a request from rlc@fnal.gov from mu2e to allow campaign keywords in various of the campaign stage values.

So for example if there is a keyword "common_version" in the campaign, you could put %(common_version)s in the version field of a campaign stage.  

I think to make that work we would have to take the udpate we're doing to formatdict here:
https://github.com/fermitools/poms/blob/main/webservice/SubmissionsPOMS.py#L1634
and expand the values, i.e. 
```
        formatdict.update(
            {
                "dataset": dataset % formatdict,
                "parameter": dataset % formatdict,
                "version": vers % formatdict,
                "group": group % formatdict,
                "experimenter": experimenter_login,
                "experiment": exp,
            }
        )
```
but there might be a few more tidbits to it I'm missing...

**Comment by LTrestka** [comment]
commit e8cb4f0610f2abc4cf8f1fec221e05d3c4f32480
